import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="from-red-300 to-pink-100 bg-gradient-to-br">
          <div className="container mx-auto">
            <Navbar />
            <div className="min-h-[calc(100vh-3.5rem)]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
